name=GyverKey
version=1.0.0
author=AlexGyver <alex@alexgyver.ru>
maintainer=AlexGyver <alex@alexgyver.ru>
sentence=Library for analog and matrix keyboards for Arduino
paragraph=Library for analog and matrix keyboards for Arduino
category=Device Control
url=https://github.com/GyverLibs/GyverKey
depends=GyverIO,uButton
architectures=*